### ISSUE TITLE
Documentation Section - Navigation Is a Bit Broken

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/apiblueprintorg#104]
https://apiblueprint.org/documentation/

The left menu is strange - the MSON link has the same url as "second” Tutorial, there are two tutorials, etc. Also the “active” state doesn’t persist on the menu item, so I don’t know where I am currently.

**Comment by kylef** [comment]
Resolved by https://github.com/apiaryio/apiblueprint.org/pull/29
