### ISSUE TITLE
"Add Your Tool" Button

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/apiblueprintorg#107]
Idea: https://apiblueprint.org/tools.html page could have a button "Add your tool", which would lead to GitHub editor, similar to "I want to be on the list" button [here](http://python.cz/en/jobs).

**Comment by kylef** [comment]
Done in https://github.com/apiaryio/apiblueprint.org/commit/e848401798950054f0ca9abab1dfd697504400a8

**Comment by honzajavorek** [comment]
:+1:
