### ISSUE TITLE
Docify link seems to be abandoned.

### ISSUE THREAD

**Issue by zanerock** [apiaryio/apiblueprintorg#65]
All the example pages linked from the docify readme 404, which has been an issue since December 2014.

**Comment by zdne** [comment]
Hey @zanerock I assume you are referring to https://github.com/tipfortip/blueprint-docify ? Not sure what seems to be error on the API Blueprint site – the link seems to be working for me – shouldn't this problem be reported at https://github.com/tipfortip/blueprint-docify instead?

**Comment by zanerock** [comment]
I wasn't very clear. The problem is the link from the Docify project page to their examples. E.g.:

http://renewablefunding.github.io/blueprint-docify/gist-fox-api/
on
https://github.com/tipfortip/blueprint-docify

There was an issue opened in the 'tipfortip/blueprint-docify' project in December 2014 pointing out the issue, but it's gone unresolved. E.g., BluePrint looks like it's broken and possibly dead and maybe should be removed from the list of projects.

**Comment by zdne** [comment]
@zanerock Gotcha. I will try to poke author and if without reply I will remove it from the listing. Thanks for pointing this out!

**Comment by kylef** [comment]
The link from apiblueprint.org to their documentation works, the link from their documentation to some examples are broken, this is tracked via https://github.com/kirkstrobeck/blueprint-docify/issues/1 and there is a pull request at https://github.com/kirkstrobeck/blueprint-docify/pull/2.

I'm going to close this as there isn't really anything broken on our side and it's a problem tracked above.
