### ISSUE TITLE
apiblueprint.org returns 404

### ISSUE THREAD

**Issue by w-vi** [apiaryio/apiblueprintorg#82]
Following link from https://apiary.io/blueprint to tooling section of apiblueprint.org site I got `404`, quick look to gh-pages branch shows that index.html is in place. Trying http://apiblueprint.org it goes to https version and returns `404`, isn't the https the problem AFAIK gh-pages are [http only](https://help.github.com/articles/what-are-github-pages/)? 
Or is it just me and everything works just fine and error is between the chair and keyboard?

**Comment by kylef** [comment]
![screen shot 2015-05-06 at 22 05 18](https://cloud.githubusercontent.com/assets/44164/7503610/00516258-f43c-11e4-901e-dd901c1bf703.png)

This error from GitHub pages, means nothing to me though.

**Comment by kylef** [comment]
Alright, I fixed this now. It must've broken early when I changed how the blog worked. GitHub pages is super fragile.

![Giphy](http://media2.giphy.com/media/12iHCgHlrPk8ko/giphy.gif)
